#!/bin/bash
# compile

# Stop on errors
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

# Sanity check command line options
usage() {
  echo "Usage: $0 (vector|linked_list|deque|all|clean)"
}

FLAGS="-Wall -Werror -Wextra -pedantic -Wshadow -Wconversion -O3 -DNDEBUG -lboost_unit_test_framework"

vector() {
  g++ vector/Vector.hpp vector/tests.cpp $FLAGS -o vector/test.exe
}

linked_list() {
  g++ linked_list/Linked_List.hpp linked_list/tests.cpp $FLAGS -o linked_list/test.exe
}

deque() {
  g++ deque/Deque.hpp deque/tests.cpp $FLAGS -o deque/test.exe
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

case $1 in
  "vector")
    vector
    ;;

  "linked_list")
    linked_list
    ;;

  "deque")
    deque
    ;;

  "all")
    vector
    linked_list
    deque
    ;;

  "clean")
    rm */test.exe
    ;;

  *)
    usage
    exit 1
    ;;
esac